#!/bin/bash

pprint (){
	cred='\033[0;31m'
	cgreen='\033[0;32m'
	cyellow='\033[0;33m'
	cblue='\033[0;34m'
	cpurple='\033[0;35m'
	eval "export color='$cpurple'"
	[ ! -z $2 ] && eval "export color=\"\$$2\""
    printf "$color $1"
}

color_reset(){ printf '\033[0;37m';}

yesnoprompt(){
	old_stty_cfg=$(stty -g)
	stty raw -echo ; answer=$(head -c 1)
	stty $old_stty_cfg
	echo "$answer" | grep -iq "^y"
}

update() {
	pprint "\n\nMemperbarui daftar paket.. "
	sudo apt update 2>&1 | grep "can be upgraded" &>/dev/null
	if [ $? -eq 0 ]; then
		pprint "PEMBARUAN TERSEDIA" "cgreen"
		pprint "\n\nApakah Anda ingin memperbarui secara otomatis (y/n)?"
		if yesnoprompt; then
			pprint "\n\nMemperbarui paket.. "
			sudo apt upgrade -y &>/dev/null &&
			pprint "SELESAI!\n\n" "cgreen" || (pprint "GAGAL.\n\n" "cred"; exit 1)
		else
			echo
		fi
	else
		pprint "SUDAH TERBARu\n\n" "cgreen"
	fi
}

packages(){
	if ! command -v pip &>/dev/null; then
		pprint "Tidak dapat menemukan pip, menginstal sekarang..."
		sudo apt install python3-pip -y 2>pypilog.txt 1>/dev/null &&
		pprint "SUKSES.\n\n" "cgreen" || (pprint "GAGAL.\n\n" "cred"; exit 1)
	fi

	if ! command -v ffmpeg &>/dev/null; then
		pprint "Tidak dapat menemukan ffmpeg, menginstal sekarang..."
		if sudo apt install ffmpeg -y &>/dev/null;then
			pprint "SUKSES.\n\n" "cgreen"
		else
			pprint "GAGAL.\n\n" "cred"
			pprint "Anda perlu menginstal ffmpeg secara manual untuk menjalankan DeltaMusic, keluar...\n" "cblue"
			exit 1
		fi
	fi

	# Check ffmpeg version and warn user if necessary.
	fv=$(grep -Po 'version (3.*?) ' <<< $(ffmpeg -version)) &&
	pprint "Memutar streaming langsung tidak akan berfungsi karena Anda memiliki ffmpeg $fv, streaming langsung didukung oleh versi 4+.\n" "cblue"
}

node(){
	command -v npm &>/dev/null && return
	pprint "Menginstal Nodejs dan Npm..  "
	curl -fssL https://deb.nodesource.com/setup_19.x | sudo -E bash - &>nodelog.txt &&
	sudo apt install -y nodejs &>>nodelog.txt &&
	sudo npm i -g npm &>>nodelog.txt &&
	pprint "SUKSES!\n" "cgreen" || (pprint "GAGAL.\n" "cred"; exit 1)
}

installation(){
	pprint "\n\nMemperbarui pip dan menginstal paket dependensi..."
	pip3 install -U pip &>>pypilog.txt &&
	pip3 install -U -r requirements.txt &>>pypilog.txt &&
	pprint "SELESAI.\n" "cgreen" && return
	pprint "GAGAL.\n" "cred"
	exit 1
}

clear
pprint "Selamat datang di Penginstal Setup DeltaMusic\n\n"
pprint "Jika Anda melihat kesalahan selama Proses Instalasi, silakan lihat file-file ini untuk log: "
pprint "\nUntuk kesalahan node js, periksa nodelog.txt"
pprint "\nUntuk kesalahan paket pypi, periksa pypilog.txt"
sleep 1
pprint "\n\nScript memerlukan hak sudo untuk memperbarui & menginstal paket.\n"
sudo test

update
packages
node
installation
pprint "\n\n\n\n\nInstalasi DeltaMusic Selesai!" "cgreen"
sleep 1
clear

pprint "\nMasukkan Nilai Anda di Bawah Ini\n\n\n"
pprint "API ID: "; color_reset; read api_id
pprint "\nAPI HASH: "; color_reset; read api_hash
pprint "\nBOT TOKEN: "; color_reset; read bot_token
pprint "\nOWNER ID:"; color_reset; read ownid
pprint "\nMONGO DB URI: "; color_reset; read mongo_db
pprint "\nLOG GROUP ID: "; color_reset; read logger
pprint "\nSTRING SESSION: "; color_reset; read string_session

pprint "\n\nMemproses variabel Anda, tunggu sebentar!" "cgreen"

if [ -f .env ]; then
	rm .env
fi

echo """API_ID = $api_id
API_HASH = $api_hash
BOT_TOKEN = $bot_token
MONGO_DB_URI = $mongo_db
LOGGER_ID = $logger
STRING_SESSION = $string_session
OWNER_ID = $ownid""" > .env
clear

pprint "\n\n\nTerima kasih telah menggunakan penginstal DeltaMusic, variabel Anda telah disimpan dengan sukses! \nJika Anda ingin menambahkan lebih banyak variabel, tambahkan di env Anda dengan: vi .env"
pprint "\n\nSekarang Anda dapat memulai bot dengan: bash start\n\n"
